import HashMap from "./HashMap.js";

const test = new HashMap();
test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
test.set("hat", "black");
test.set("ice cream", "white");
test.set("jacket", "blue");
test.set("kite", "pink");
test.set("lion", "golden");

console.log(test.printHashMap());
console.log(`size:`);
console.log(test.length());
console.log(`get apple: ` + test.get("apple"));
console.log(`get banana: ` + test.get("banana"));
console.log(`get strawberry: ` + test.get("strawberry"));
console.log(`has dog: ` + test.has("dog"));
console.log(`has cat: ` + test.has("cat"));
console.log(`remove dog from map`);
test.remove("dog");
console.log(`has dog: ` + test.has("dog"));
console.log(`size:`);
console.log(test.length());
// console.log(test.clear());
console.log(`keys: `);
console.log(test.keys());
console.log(`values: `);
console.log(test.values());
console.log(`entries: `);
console.log(test.entries());
console.log(`Add new values and resize if exceeds load factor: `);
test.set("dog", "brown");
test.set("moon", "silver");
console.log(test.printHashMap());
console.log(test.length());
