import LinkedList from "./LinkedList.js";

const list = new LinkedList();
console.log(`Prepend nodes to the list`);
list.prepend(1);
list.prepend(2);
list.prepend(3);
console.log(list.toString());
console.log(`Is the list empty? ` + list.isEmpty());
console.log(`Size: ` + list.size());
console.log(`Head: ` + list.listHead());
console.log(`Tail: ` + list.tail());
console.log(`Append node to the list`);
list.append(6);
console.log(list.toString());
console.log(`Size: ` + list.size());
console.log(`Head: ` + list.listHead());
console.log(`Tail: ` + list.tail());
console.log(`Value at index 0: ` + list.at(0));
console.log(`Value at index 3: ` + list.at(3));
console.log(`Value at index 4: ` + list.at(4));
console.log(`Remove the last element`);
list.pop();
console.log(list.toString());
console.log(`Is value 3 in the list? ` + list.contains(3));
console.log(`Is value 1 in the list? ` + list.contains(1));
console.log(`Is value 6 in the list? ` + list.contains(6));
console.log(`Index of value 3: ` + list.find(3));
console.log(`Index of value 1: ` + list.find(1));
console.log(`Index of value 4: ` + list.find(4));
console.log(`Remove element at index 0 `);
list.removeAt(0);
console.log(list.toString());
console.log(`Remove element at index 1 `);
list.removeAt(1);
console.log(list.toString());
console.log(`Remove element at index 2 `);
list.removeAt(2);
console.log(list.toString());
console.log(`Remove element at index 0 `);
list.removeAt(0);
console.log(list.toString());
console.log(`Insert at index 0, 1`);
list.insertAt("hello", 0);
list.insertAt("world", 1);
console.log(list.toString());
console.log(`Insert at index 0, 1 and 25`);
list.insertAt(1, 0);
list.insertAt(2, 1);
list.insertAt(3, 25);
console.log(list.toString());
